version: '3.7'

networks:
  app-network:
    driver: bridge

services:
  planning-front-end:
    image: dvorobiev1968/planning-front-end:latest
    container_name: planning-front-end
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      app-network:
    ports:
      - 8081:80
    volumes:
      - /var/log/nginx:/var/log
